version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - mynetwork
  app:
    image: identity:local
    networks:
      - mynetwork
    ports:
      - "5000:80"
networks:
  mynetwork:
    driver: bridge
